name: Tests

on:
    pull_request:
    push:


jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   uses: actions/setup-node@v3
                with:
                    node-version: 16
                    cache: 'npm'
                    cache-dependency-path: package-lock.json

            -   name: NPM install
                run: npm ci

            -   name: Lint
                run: npm run lint:check

            -   name: Code style
                run: npm run format:check

            -   name: Test
                run: npm run test
